//// C STANDARD LIBRARIES
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

//// LINUX STANDARD LIBRARIES
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>

//// WAYLAND SPECIFIC LIBRARIES
#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

//// AUTOGENERATED WAYLAND INTERFACES
#include "xdg-shell-client-protocol.h"
#include "xdg-shell-protocol.c"

typedef struct wl_display * Display;
typedef struct wl_registry * Registry;
typedef struct wl_surface * Surface;
typedef struct wl_compositor * Compositor;
typedef struct wl_interface Interface;
typedef struct wl_seat * Seat;
typedef struct wl_shm * Shm;
typedef struct wl_shm_pool * Pool;
typedef struct wl_buffer * Buffer;
typedef struct xdg_wm_base * XdgBase;
typedef struct xdg_surface * XdgSurface;
typedef struct xdg_toplevel * XdgToplevel;

//// STATE

typedef struct {
    int fd;
    size_t size;
    Pool pool;
    uint32_t * pixels;
    Buffer buffer;
    bool active;
} FrameBuffer;

typedef struct {

    /*Wayland Objects*/
    Compositor compositor;
    Seat seat;
    Shm shm;
    XdgBase xdg_base;

    /*Manually Set Variables*/
    Display display;
    Surface surface;
    XdgSurface xdg_surface;
    XdgToplevel xdg_toplevel;

    /*Frame Buffers*/
    FrameBuffer front;
    FrameBuffer back;

    /*Application State*/
    bool quit;
    int width;
    int height;
} State;

//// SHM

static int shm_file_allocate(size_t size) {
    static char name[1024] = {0};
    snprintf(name, sizeof(name), "/wayland-shm-%d-%d", getpid(), rand());
    int fd = shm_open(name, O_RDWR | O_CREAT | O_EXCL, 0600);
    assert(fd >= 0);
    shm_unlink(name);
    ftruncate(fd, size);
    return fd;
}

FrameBuffer frame_buffer_allocate(Shm shm, size_t width, size_t height) {
    FrameBuffer result = {0};
    const size_t stride = width * 4;
    result.size = stride * height;
    result.fd = shm_file_allocate(result.size);
    result.pixels = mmap(NULL, result.size, PROT_READ | PROT_WRITE, MAP_SHARED, result.fd, 0);
    assert(result.pixels != MAP_FAILED);
    result.pool = wl_shm_create_pool(shm, result.fd,result.size);
    result.buffer = wl_shm_pool_create_buffer(result.pool, 0, width, height, stride, WL_SHM_FORMAT_XRGB8888);

    /*safe to close fd after pool is created*/
    close(result.fd);
    return result;
}

//// REGISTRY

void registry_listener_global (
    void * data,
    Registry r,
    uint32_t name,
    const char * interface,
    uint32_t version
) {
    State * state = data;
    
    #define BIND(wl_interface, dest) \
        if(strcmp(interface, wl_interface.name) == 0) {                 \
            dest = wl_registry_bind(r, name, &wl_interface, version);   \
            printf("Bound global: %s\n", interface);                    \
            return;                                                     \
        }

    BIND(wl_compositor_interface, state->compositor);
    BIND(wl_seat_interface, state->seat);
    BIND(wl_shm_interface, state->shm);
    BIND(xdg_wm_base_interface, state->xdg_base);

    #undef BIND
}

void registry_listener_global_remove (
    void * data,
    Registry r,
    uint32_t name
) {
    /*TODO*/
}

//// BUFFER

static void wl_buffer_release(void *data, struct wl_buffer *wl_buffer){
    /* Sent by the compositor when it's no longer using this buffer */
    wl_buffer_destroy(wl_buffer);
}


//// XDG
static void xdg_wm_base_ping(void *data, XdgBase b, uint32_t serial){
    xdg_wm_base_pong(b, serial);
}

static void xdg_surface_configure(void *data, XdgSurface xdg_surface, uint32_t serial){
    State *state = data;
    xdg_surface_ack_configure(xdg_surface, serial);

    // TODO: remove this call and factor this into the main loop
    FrameBuffer test = frame_buffer_allocate(state->shm, 200, 200);
    wl_surface_attach(state->surface, test.buffer, 0, 0);
    wl_surface_commit(state->surface);
}

static void
xdg_toplevel_configure(void *data,
		struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height,
		struct wl_array *states)
{
    State * state = data;
	if (width == 0 || height == 0) {
		/* Compositor is deferring to us */
		return;
	}
	state->width = width;
	state->height = height;
}

static void
xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel)
{
    State * state = data;
    state->quit = true;
}

void xdg_toplevel_configure_bounds(void *data, XdgToplevel xdg_toplevel, int32_t width, int32_t height) {
    printf("resize requested");
}

void xdg_toplevel_wm_capabilities(void *data, XdgToplevel xdg_toplevel, struct wl_array *capabilities) {

    printf("TODO: list capabilities");
}


//// MAIN

int main() {
    State state = {0};
    state.display = wl_display_connect(NULL);
    Registry registry = wl_display_get_registry(state.display);
    wl_registry_add_listener(
        registry,
        &(struct wl_registry_listener){
            .global = registry_listener_global,
            .global_remove = registry_listener_global_remove
        },
        &state
    );
    wl_display_roundtrip(state.display);
    xdg_wm_base_add_listener(
        state.xdg_base,
        &(struct xdg_wm_base_listener){
            .ping = xdg_wm_base_ping
        },
        &state
    );

    /*XDG STUFF*/
    state.surface = wl_compositor_create_surface(state.compositor);
    state.xdg_surface = xdg_wm_base_get_xdg_surface(state.xdg_base, state.surface);
    xdg_surface_add_listener(
        state.xdg_surface,
        &(struct xdg_surface_listener){
            .configure = xdg_surface_configure,
        },
        &state
    );
    state.xdg_toplevel = xdg_surface_get_toplevel(state.xdg_surface);
    xdg_toplevel_add_listener(
        state.xdg_toplevel,
        &(struct xdg_toplevel_listener){
            .configure = xdg_toplevel_configure,
            .close = xdg_toplevel_close,
            .configure_bounds = xdg_toplevel_configure_bounds,
            .wm_capabilities = xdg_toplevel_wm_capabilities,
        },
        &state
    );
    xdg_toplevel_set_title(state.xdg_toplevel, "Example client");
    wl_surface_commit(state.surface);
    

    while (wl_display_dispatch(state.display)) {
        /* This space deliberately left blank */
    }


 }
