//// C STANDARD LIBRARIES
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

//// LINUX STANDARD LIBRARIES
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>

//// WAYLAND SPECIFIC LIBRARIES
#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

//// AUTOGENERATED WAYLAND INTERFACES
#include "xdg-shell-client-protocol.h"
#include "xdg-shell-protocol.c"

#define UNUSED(variable) (void)(variable)
#define TODO(msg) assert(0 && msg)

typedef struct wl_display * Display;
typedef struct wl_registry * Registry;
typedef struct wl_surface * Surface;
typedef struct wl_compositor * Compositor;
typedef struct wl_interface Interface;
typedef struct wl_seat * Seat;
typedef struct wl_shm * Shm;
typedef struct wl_shm_pool * Pool;
typedef struct wl_buffer * Buffer;
typedef struct xdg_wm_base * XdgBase;
typedef struct xdg_surface * XdgSurface;
typedef struct xdg_toplevel * XdgToplevel;

//// STATE

typedef struct {
    int32_t width;
    int32_t height;
    uint32_t * pixels;
    Buffer buffer;
    bool active;
} FrameBuffer;

typedef struct {

    /*Wayland Objects*/
    Compositor compositor;
    Seat seat;
    Shm shm;
    XdgBase xdg_base;

    /*Manually Set Variables*/
    Display display;
    Registry registry;
    Surface surface;
    XdgSurface xdg_surface;
    XdgToplevel xdg_toplevel;

    /*Frame Buffers*/
    FrameBuffer front_buffer;
    FrameBuffer back_buffer;

    /*Application State*/
    bool quit;
    bool next_frame;
    int width;
    int height;
} State;

//// SHM

static int shm_file_allocate(size_t size) {
    static char name[1024] = {0};
    snprintf(name, sizeof(name), "/wayland-shm-%d-%d", getpid(), rand());
    int fd = shm_open(name, O_RDWR | O_CREAT | O_EXCL, 0600);
    assert(fd >= 0);
    shm_unlink(name);
    ftruncate(fd, size);
    return fd;
}

static size_t frame_buffer_calculate_needed_size(size_t width, size_t height) {
   const int stride = width * 4;
   return stride * height;
}

FrameBuffer frame_buffer_allocate(Shm shm, size_t width, size_t height) {
    FrameBuffer result = {0};
    result.width = width;
    result.height = height;
    const int size = frame_buffer_calculate_needed_size(result.width, result.height);
    const int fd = shm_file_allocate(size);
    result.pixels = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    assert(result.pixels != MAP_FAILED);
    Pool pool = wl_shm_create_pool(shm, fd, size);
    result.buffer = wl_shm_pool_create_buffer(pool, 0, result.width, result.height,
                                              result.width * 4, WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);
    return result;
}

void frame_buffer_free(FrameBuffer buf) {
    munmap(buf.pixels, frame_buffer_calculate_needed_size(buf.width, buf.height));
    wl_buffer_destroy(buf.buffer);
}

//// REGISTRY

void registry_listener_global (
    void * data,
    Registry r,
    uint32_t name,
    const char * interface,
    uint32_t version
) {
    State * state = data;
    
    #define BIND(wl_interface, dest) \
        if(strcmp(interface, wl_interface.name) == 0) {                 \
            dest = wl_registry_bind(r, name, &wl_interface, version);   \
            printf("Bound global: %s\n", interface);                    \
            return;                                                     \
        }

    BIND(wl_compositor_interface, state->compositor);
    BIND(wl_seat_interface, state->seat);
    BIND(wl_shm_interface, state->shm);
    BIND(xdg_wm_base_interface, state->xdg_base);

    #undef BIND
}

void registry_listener_global_remove (
    void * data,
    Registry r,
    uint32_t name
) {
    UNUSED(data);
    UNUSED(r);
    UNUSED(name);
    /*TODO*/
}

//// BUFFER

static void wl_buffer_release(void *data, struct wl_buffer *wl_buffer){
    UNUSED(data);
    TODO("handle this call");
    /* Sent by the compositor when it's no longer using this buffer */
    wl_buffer_destroy(wl_buffer);
}


//// XDG
static void xdg_wm_base_ping(void *data, XdgBase b, uint32_t serial){
    UNUSED(data);
    xdg_wm_base_pong(b, serial);
}

static void xdg_surface_configure(void *data, XdgSurface xdg_surface, uint32_t serial){
    UNUSED(data);
    xdg_surface_ack_configure(xdg_surface, serial);
}

static void
xdg_toplevel_configure(void *data,
		struct xdg_toplevel *xdg_toplevel, int32_t width, int32_t height,
		struct wl_array *states)
{
    UNUSED(xdg_toplevel);
    UNUSED(states);
    State * state = data;
	if (width == 0 || height == 0) {
		/* Compositor is deferring to us */
		return;
	}
	state->width = width;
	state->height = height;
}

static void
xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel)
{
    UNUSED(toplevel);
    State * state = data;
    state->quit = true;
}

void xdg_toplevel_configure_bounds(void *data, XdgToplevel xdg_toplevel, int32_t width, int32_t height) {
    UNUSED(xdg_toplevel);
    State * state = data;
    state->width = width;
    state->height = height;
    if(state->front_buffer.pixels != NULL) {
        frame_buffer_free(state->front_buffer);
    }
    if(state->back_buffer.pixels != NULL) {
        frame_buffer_free(state->back_buffer);
    }
    state->front_buffer = frame_buffer_allocate(state->shm, state->width, state->height);
    state->back_buffer = frame_buffer_allocate(state->shm, state->width, state->height);
    
}

void xdg_toplevel_wm_capabilities(void *data, XdgToplevel xdg_toplevel, struct wl_array *capabilities) {

    printf("TODO: list capabilities");
}

//// FRAME
static void frame_listener_done(void *data, struct wl_callback *cb, uint32_t time_ms) {
    State * state = data;
    printf("ms: %u\n", time_ms);
    wl_callback_destroy(cb);
    state->next_frame = true;
}


//// INIT

void state_init(State * out) {
    out->display = wl_display_connect(NULL);
    Registry registry = wl_display_get_registry(out->display);
    out->registry = registry;
    static const struct wl_registry_listener registry_listener = {
        .global = registry_listener_global,
        .global_remove = registry_listener_global_remove
    };
    wl_registry_add_listener(registry, &registry_listener, out);
    wl_display_roundtrip(out->display);

    static const struct xdg_wm_base_listener base_listener = {
        .ping = xdg_wm_base_ping
    };
    xdg_wm_base_add_listener(out->xdg_base, &base_listener, out);

    /*XDG STUFF*/
    out->surface = wl_compositor_create_surface(out->compositor);
    out->xdg_surface = xdg_wm_base_get_xdg_surface(out->xdg_base, out->surface);
    static const struct xdg_surface_listener surface_listener = {
        .configure = xdg_surface_configure
    };
    xdg_surface_add_listener(out->xdg_surface, &surface_listener, out);
    out->xdg_toplevel = xdg_surface_get_toplevel(out->xdg_surface);
    static const struct xdg_toplevel_listener toplevel_listener = {
        .configure = xdg_toplevel_configure,
        .close = xdg_toplevel_close,
        .configure_bounds = xdg_toplevel_configure_bounds,
        .wm_capabilities = xdg_toplevel_wm_capabilities
    };
    xdg_toplevel_add_listener(out->xdg_toplevel, &toplevel_listener, out);
    xdg_toplevel_set_title(out->xdg_toplevel, "Example client");
    wl_surface_commit(out->surface);
    wl_display_roundtrip(out->display);

    //Create FrameBuffers
    printf("allocated buffers of size: %d, %d\n", out->width, out->height);
    out->front_buffer = frame_buffer_allocate(out->shm, out->width, out->height);
    out->back_buffer = frame_buffer_allocate(out->shm, out->width, out->height);
    wl_callback_add_listener(wl_surface_frame(out->surface), &(struct wl_callback_listener){.done = frame_listener_done}, out);
    wl_surface_attach(out->surface, out->front_buffer.buffer, 0, 0);
    wl_surface_commit(out->surface);
    wl_display_roundtrip(out->display);
    out->next_frame = true;
}

void state_deinit(State * state) {
    frame_buffer_free(state->front_buffer);
    frame_buffer_free(state->back_buffer);
    wl_registry_destroy(state->registry);
    wl_display_disconnect(state->display);
 }

//// MAIN

int main() {
    State state = {0};
    state_init(&state);
    int foo = 10;
    int mod_foo = 1;
    while (!state.quit) {
        
        if(state.next_frame) {
            state.next_frame = false;

            /* render / attach / commit as you already do */
            for(int x = 0; x < state.back_buffer.width; ++x) {
                for(int y = 0; y < state.back_buffer.height; ++y) {
                    if(x % foo == 0) {
                        state.back_buffer.pixels[y * state.back_buffer.width + x] = 0x00FFFFFF;
                    } else {
                        if(y / foo > 3) {
                            state.back_buffer.pixels[y * state.back_buffer.width + x] = 0x000000;
                        } else {
                            state.back_buffer.pixels[y * state.back_buffer.width + x] = 0x00FFFFFF;
                        }
                    }
                }
            }
            foo += mod_foo;
            if(foo > 150 || foo < 10) mod_foo *= -1;
    
            FrameBuffer temp = state.front_buffer;
            state.front_buffer = state.back_buffer;
            state.back_buffer = temp;
            //TODO handle resizing
    
            wl_callback_add_listener(wl_surface_frame(state.surface), &(struct wl_callback_listener){.done = frame_listener_done}, &state);
            wl_surface_damage(state.surface, 0, 0, 10000, 10000);
            wl_surface_attach(state.surface, state.front_buffer.buffer, 0, 0);
            wl_surface_commit(state.surface);

            wl_display_flush(state.display);
        }
        wl_display_dispatch(state.display);
    }
    state_deinit(&state);
}
