//// C STANDARD LIBRARIES
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

//// LINUX STANDARD LIBRARIES
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>

//// WAYLAND SPECIFIC LIBRARIES
#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

//// AUTOGENERATED WAYLAND INTERFACES
#include "xdg-shell-client-protocol.h"
#include "xdg-shell-protocol.c"

typedef struct wl_display * Display;
typedef struct wl_registry * Registry;
typedef struct wl_surface * Surface;
typedef struct wl_compositor * Compositor;
typedef struct wl_interface Interface;
typedef struct wl_seat * Seat;
typedef struct wl_shm * Shm;
typedef struct xdg_wm_base * Base;
typedef struct xdg_surface * XdgSurface;

//// STATE

typedef struct {
    Compositor c;
    Seat s;
    Shm m;
    Base b;

    Display d;
    Surface sf;
} State;

//// SHM

static int allocate_shm_file(size_t size) {
    static char name[1024] = {0};
    snprintf(name, sizeof(name), "/wayland-shm-%d-%d", getpid(), rand());
    int fd = shm_open(name, O_RDWR | O_CREAT | O_EXCL, 0600);
    assert(fd >= 0);
    shm_unlink(name);
    ftruncate(fd, size);
    return fd;
}

//// REGISTRY

void registry_listener_global (
    void * data,
    Registry r,
    uint32_t name,
    const char * interface,
    uint32_t version
) {
    State * state = data;
    
    #define BIND(wl_interface, dest) \
        if(strcmp(interface, wl_interface.name) == 0) {                 \
            dest = wl_registry_bind(r, name, &wl_interface, version);   \
            printf("Bound global: %s\n", interface);                    \
            return;                                                     \
        }

    BIND(wl_compositor_interface, state->c);
    BIND(wl_seat_interface, state->s);
    BIND(wl_shm_interface, state->m);
    BIND(xdg_wm_base_interface, state->b);

    #undef BIND
}

void registry_listener_global_remove (
    void * data,
    Registry r,
    uint32_t name
) {
    /*TODO*/
}

//// BUFFER

static void wl_buffer_release(void *data, struct wl_buffer *wl_buffer){
    /* Sent by the compositor when it's no longer using this buffer */
    wl_buffer_destroy(wl_buffer);
}

static struct wl_buffer *
draw_frame(State * state)
{
    const int width = 640, height = 480;
    int stride = width * 4;
    int size = stride * height;

    int fd = allocate_shm_file(size);
    if (fd == -1) {
        return NULL;
    }

    uint32_t *data = mmap(NULL, size,
            PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED) {
        close(fd);
        return NULL;
    }

    struct wl_shm_pool *pool = wl_shm_create_pool(state->m, fd, size);
    struct wl_buffer *buffer = wl_shm_pool_create_buffer(pool, 0,
            width, height, stride, WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);

    /* Draw checkerboxed background */
    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            if ((x + y / 8 * 8) % 16 < 8)
                data[y * width + x] = 0xFF666666;
            else
                data[y * width + x] = 0xFFEEEEEE;
        }
    }

//    munmap(data, size);
    static struct wl_buffer_listener buflisten = {.release = wl_buffer_release };
    wl_buffer_add_listener(buffer, &buflisten, NULL);
    return buffer;
}

//// XDG
static void xdg_wm_base_ping(void *data, Base b, uint32_t serial){
    xdg_wm_base_pong(b, serial);
}

static void xdg_surface_configure(void *data, XdgSurface xdg_surface, uint32_t serial){
    State *state = data;
    xdg_surface_ack_configure(xdg_surface, serial);

    struct wl_buffer *buffer = draw_frame(state);
    wl_surface_attach(state->sf, buffer, 0, 0);
    wl_surface_commit(state->sf);
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

//// MAIN

int main() {
    State state = {0};
    state.d = wl_display_connect(NULL);
    Registry registry = wl_display_get_registry(state.d);
    wl_registry_add_listener(
        registry,
        &(struct wl_registry_listener){
            .global = registry_listener_global,
            .global_remove = registry_listener_global_remove
        },
        &state
    );
    wl_display_roundtrip(state.d);
    xdg_wm_base_add_listener(
        state.b,
        &(struct xdg_wm_base_listener){
            .ping = xdg_wm_base_ping
        },
        &state
    );

    state.sf = wl_compositor_create_surface(state.c);
    XdgSurface xdg_surface = xdg_wm_base_get_xdg_surface(state.b, state.sf);
    xdg_surface_add_listener(
        xdg_surface,
        &(struct xdg_surface_listener){
            .configure = xdg_surface_configure
        },
        &state
    );
    struct xdg_toplevel *toplevel = xdg_surface_get_toplevel(xdg_surface);
    xdg_toplevel_set_title(toplevel, "my-wl-client");
    wl_surface_commit(state.sf);

    while (wl_display_dispatch(state.d)) {
        /* This space deliberately left blank */
    }


 }
 
